spring.application.name=Session20_Bai1


#Config Datasource
spring.datasource.driver-class-name=com.mysql.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/session20?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=admin123

#Config JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true


# Cấu hình JWT Security
# Chuỗi Secret Key dạng Base64 (bắt buộc có độ dài tối thiểu 256-bit / 32 ký tự đối với thuật toán HS256)
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970

# Thời gian sống của Access Token: 10 phút (10 * 60 * 1000 miligiây)
jwt.access-expiration=600000

# Thời gian sống của Refresh Token: 3 ngày (3 * 24 * 60 * 60 * 1000 miligiây)
jwt.refresh-expiration=259200000